# Example Site settings

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

plugins:
  - jekyll-seo-tag
  - jekyll-admin

tracking: true
csp_extra: "https://plausible.vektogram.com"


# Theme options
# style: dark # dark (default) or light or hacker
# listen_for_clients_preferred_style: true # true or false (default)

# Fonts
# disable_google_fonts: false # set true to prevent loading fonts.googleapis.com

# Tracking (generic, optional; loads only in production)
# tracking:
#   script_src:
#     - https://analytics.example.com/matomo.js
#   async: true   # default true
#   defer: false  # default false
#   # Optional inline init snippet (requires CSP allowance if used)
#   # init: |
#   #   var _paq = window._paq = window._paq || [];
#   #   _paq.push(['trackPageView']);
#   #   _paq.push(['enableLinkTracking']);
#   #   _paq.push(['setTrackerUrl', 'https://analytics.example.com/matomo.php']);
#   #   _paq.push(['setSiteId', '1']);
#
# # Extend CSP to allow your tracker sources (script-src/connect-src/img-src as needed)
# # csp_extra: "script-src 'self' https://analytics.example.com; connect-src 'self' https://analytics.example.com; img-src 'self' https://analytics.example.com;"
